### ISSUE TITLE
mobile false not working

### ISSUE THREAD

**Issue by Ataurr** [matthieua/WOW#119]
hi 
i have tried to off effect but its not working

```js
var wow = new WOW( {
    mobile:    false
  });
wow.init();
```

i have tried with android mobile
can you please check. why its not working on mobile device.

Thanks in advance

**Comment by ShaunGuarini** [comment]
Isn't xpeeder confusing animate.css with wow?

Should mobile false stop animations all together or should it only stop the wow reveal part (offset, delay, etc.).

**Comment by graywizzard** [comment]
I am using the following solution.

// Small Screen
if(windowWidth <= 719){
	$(document).ready(function() {
		$(".wow").removeClass("wow");
	});
}

**Comment by Ataurr** [comment]
if you are using wow latest version its work fine.

**Comment by douglace** [comment]
I use this solution
`@media screen and (max-width: 800px) {
    .wow{
        animation-name: none !important;
        visibility: visible !important;
    }
}`

**Comment by wtt19980923** [comment]
I was revise "this.defaults.mobile = false" in wow.js but it not worked in phone,the animate also done. : (
