### ISSUE TITLE
Disable WOW.js on IE8

### ISSUE THREAD

**Issue by simondoescode** [matthieua/WOW#142]
Is there a way to disable WOW.js on IE8?

**Comment by designorant** [comment]
Here's a shorter way for those who don't want to use Modernizr:

````html
<!--[if gt IE 8]><!-->
<script>
    new WOW().init();
</script>
<!--<![endif]-->
````

**Comment by cjmosure** [comment]
CSS3 animation doesn't seem to be supported by IE9, see http://caniuse.com/#feat=css-animation, so maybe use `<!--[if gt IE 9]><!-->`

**Comment by vinayak5192** [comment]
To disable Wow on IE8 or any other IE browsers what I did is > 
make conditional css file for particulat IE
also create conditional IE for Div and copy the div in it and remove wow classes. 
On original div assign class ( any)  and in IE css make the div display none. 

Your Conditional IE Div will be visible and div with wow class will be hidden in IE. 
Longcut but that worked for me.

**Comment by meebwolf** [comment]
Probably not very elegant - but here is what I do in angular

```
.config(['$windowProvider', function($windowProvider) {
    var $window = $windowProvider.$get();
    var userAgent = $window.navigator.userAgent;
    var notCompatible = /^((?!chrome|android|safari).)*trident/i.test(userAgent);
    if (!notCompatible) {
      new WOW().init();
    }
  }])
```
