### ISSUE TITLE
position resets after adding an extra :hover animation

### ISSUE THREAD

**Issue by modstudio** [matthieua/WOW#163]
I'm adding an extra :hover to my class, 
however it fires off, but resets automatically when finshed. 

(Example scss) 
```css
.nudge-up {
  @include transition(transform .2s ease-in-out);
  &:hover {
    @include transform(translate(0px, -5px));
  }
}
```

i wish for it to stick until i loose focus, when i remove my WOW js init, this is the desired behavour.

**Comment by modstudio** [comment]
ok, i've solved my problem, could this be considered a bug? 

```css
.nudge-up {
  @include transition(transform .2s ease-in-out);
  &:hover {
    @include animation(0);
    @include transform(translate(0px, -5px));
  }
}
```
should it automatically stop any animations after finished? or would this be an animate.css issue?

**Comment by mdeboer** [comment]
Afaik it's a WOW 'issue' as it doesn't remove the animated class once the animation is complete. For now use your fix, I'll see if I can fix this and I'll do a pull request.

Would you mind giving it a spin when I fixed it? :+1:

**Comment by modstudio** [comment]
ok thansk, and of course :)

**Comment by mdeboer** [comment]
@modstudio please see my commit / pull request. Should have fixed your issue. I tried removing the animated class after animation has ended in my browser first, after that hovering with a transform worked correctly so now I included it in WOW.

https://github.com/mdeboer/WOW/commit/8aca072d0df3a68b7fb0760a9e4a2db5a23c56ca

**Comment by modstudio** [comment]
Great. Works fine. It's funny becauses that error only shows up in Safari on my system.. Firefox seems figure it all out... thanks for the quick fix!
