### ISSUE TITLE
Animted many times on up scrolling and bottom strolling

### ISSUE THREAD

**Issue by DjSunrise** [matthieua/WOW#168]
How can I make infinitely animation instead 1 time ?

**Comment by attilaolah** [comment]
You mean animate again when the user scrolls back? See #167.

If you just want to kick off an animation once the item becomes visible and keep animating it, set [`animation-iteration-count: infinite`][1].

[1]: //developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count
