### ISSUE TITLE
infinite loop (iteration)

### ISSUE THREAD

**Issue by mvanleest** [matthieua/WOW#170]
It would be nice to be able to create a never ending animation with the setting data-wow-iteration="-1".
This is useful for the pulse animation for instance.

Or am I missing a setting?

**Comment by mvanleest** [comment]
Never mind! providing "infinite" did the trick...

**Comment by attilaolah** [comment]
Yep, and [here's why][1].

[1]: //developer.mozilla.org/en-US/docs/Web/CSS/animation-iteration-count#Syntax
