### ISSUE TITLE
Error on animation end

### ISSUE THREAD

**Issue by brianchirls** [matthieua/WOW#172]
The `config` object referenced inside [`resetAnimation`](https://github.com/matthieua/WOW/blob/master/src/wow.coffee#L207) is `undefined` because it's referencing an undeclared variable. It should refer to the `config` property on the `WOW` object.

Be careful here, because `this` in the context of `resetAnimation` refers to the source of the event, which I believe is `box`. One possible solution is to bind `@resetAnimation` to `this` when it's passed to `addEvent` inside `show`. That might become a problem if you ever want to remove the 'animationend' event handler. Maybe someone else may be able to come up with a more elegant approach.

**Comment by chedched** [comment]
+1

**Comment by ItsJonQ** [comment]
+1 on this as well

**Comment by brianchirls** [comment]
:+1:

**Comment by ckizer** [comment]
How do I install this fix? Seeing the same issues.
