### ISSUE TITLE
wow.js happens on page load and not on scroll

### ISSUE THREAD

**Issue by gaumji** [matthieua/WOW#190]
We have deployed a new design to our website . I'm using wow.js, and it works fine, except the animations all happen immediately after the page load, and not when they are scrolled to. I followed the docs, but can't figure it out.

Its working fine in pure html :  http://developer.groupdesign.in/saivision/html_changes/index.html

But when I implemented the same in our Codeigniter based application its stopped working on scroll and work on page load only :   http://taskit.co.za/index.php/

Pls help out

**Comment by matthieua** [comment]
Just don't include the `animated` class on your `wow` elements.
