### ISSUE TITLE
Add animate.css on main attribute on .bower.json file

### ISSUE THREAD

**Issue by pablodgonzalez** [matthieua/WOW#208]
Why animate.css is not in main attribute of .bower.json file? Can you add this?

**Comment by attilaolah** [comment]
I'm no expert for bower, we should probably ask @matthieua, but my guess is that it's because `animate.css` is is an (optional) dependency, not part of this library. WOW.js works well with `animate.css`, but works just as well without it (you can provide native or custom animations).

**Comment by pablodgonzalez** [comment]
@attilaolah thanks for you answer, @matthieua  sorry close this issue.
