### ISSUE TITLE
bootstrap carousel

### ISSUE THREAD

**Issue by mbtocalli** [matthieua/WOW#210]
I am using native bootstrap carousel and Wow.js
I am trying to create a carousel where the contents of each slide animates when the slide is active. Is there a way I can change it so the animation occurs on the content only when its containing slide is visible on the screen?

**Comment by webdizajner** [comment]
http://www.sitepoint.com/bootstrap-carousel-with-css3-animations/

**Comment by attilaolah** [comment]
I hope that answers your question, @mbtocalli. Feel free to reopen if it doesn't.
