### ISSUE TITLE
Convert to composer package

### ISSUE THREAD

**Issue by KarloxMartinez** [matthieua/WOW#212]
Please convert this in the composer package for install with:
composer requiere matthieua/wow

thanks

**Comment by lucidlemon** [comment]
composer is for PHP, wow is js so it is meant to be installed with bower, which it does.

`bower install wowjs`

**Comment by attilaolah** [comment]
Yep. Works as intended.

**Comment by KarloxMartinez** [comment]
I need use with the symfony2, no with bower

**Comment by lucidlemon** [comment]
symfony is php, wow.js is javascript. composer is not, in any way, meant
for js. not at all. You need to use bower for JS and css. You will never
ever ever ever see wow.js on composer.

**Comment by KarloxMartinez** [comment]
Jquery is javascript, se the  URL https://packagist.org/packages/components/jquery for composer install

**Comment by QWp6t** [comment]
That package is managed by a third-party, not jQuery. You can request that the same group create a repo for wow.js here: https://github.com/components/components/issues

Apart from that, like everyone else said, Composer is a PHP dependency and package manager, not a JavaScript one. Requesting this here is patently absurd.
