### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by Jadaw1n** [matthieua/WOW#228]
Would be nice to have wowjs as npm package!

**Comment by etylsarin** [comment]
+1

**Comment by conor** [comment]
+1

**Comment by roylodder** [comment]
+1

**Comment by n0m4dz** [comment]
+1

**Comment by benjasHu** [comment]
+1

**Comment by jasonlam0619** [comment]
+1

**Comment by Firfi** [comment]
There's already wow package in npm actually (`npm info wow`) but it is another 'wow', not this 'wow. Just for maintainer information.

+1

**Comment by jlmakes** [comment]
This would be simple enough! A properly formed `package.json` followed by `npm publish` from the author would handle this almost immediately.

**Comment by saviomd** [comment]
It would be nice but it doesn't need to.
You can reference github projects instead of npm packages in your package.json:
```
"dependencies": {
  "wow": "matthieua/WOW#1.1.2"
}
```
(I always refer to a specific tag, but I think that you can take "#1.1.2" off and it will get the master instead)

**Comment by jasonlam0619** [comment]
@saviomd Good solution. Yet I have failed to require it after installation. Do you know how to require the module this way properly?

**Comment by jlmakes** [comment]
@saviomd You need it wrapped in a module loader. I think you want to look into the [AMD branch](https://github.com/matthieua/WOW/tree/amd).

**Comment by saviomd** [comment]
@jasonlam0619 I don't know..
I don't use require.js/module loaders (yeah, I know, I need to get into this..).
I normally concat it with other "external" scripts using gulp:
```
return gulp.src([
		'node_modules/jquery/dist/jquery.js',
		'node_modules/jquery-smooth-scroll/jquery.smooth-scroll.js',
		'node_modules/wow/dist/wow.js'
	])
	.pipe(concat('vendor.js'))
```

But probably @jlmakes solution will do for you :)

**Comment by rstacruz** [comment]
Can we publish this as `wow.js`? :+1:

**Comment by graingert** [comment]
@rstacruz I've published this to wow.js, @matthieua feel free to send me your NPM details and I'll switch the project over to you

**Comment by rstacruz** [comment]
neat!

**Comment by e-cloud** [comment]
that would be very nice to publish wow to npm as many other FE libraries did.
and it need adding a file to export it.

One more, @matthieua , there is a dependency which is `animate.css` missing in `bower.json`

**Comment by cusspvz** [comment]
+1

**Comment by graingert** [comment]
@cusspvz you can "npm install wow.js"

**Comment by matthieua** [comment]
I've just publsihed it under `wowjs`, sorry for being that slowow.
https://www.npmjs.com/package/wowjs

**Comment by graingert** [comment]
@matthieua do you want access to wow.js ?

**Comment by matthieua** [comment]
@graingert it's fine, can you delete it maybe?

**Comment by graingert** [comment]
@matthieua actually I'm keeping it as I need it under the MIT. Sorry

**Comment by cusspvz** [comment]
@matthieua thanks for publishing it!
Meanwhile, I can't use it because it isn't exporting the `WOW` constructor by default, could you please implement an UMD loading instead?

Do you want me to help you with that process?

**Comment by cusspvz** [comment]
Well, just did it. Please a look at it.

**Comment by graingert** [comment]
@cusspvz `npm install wow.js` supports UMD and is MIT licensed. It will always be free to use with proprietary software

**Comment by cusspvz** [comment]
@graingert I've seen that you've made lots of changes on it. I've regarded all the pros and cons and I prefer to use my local version (the day I've commented I just grabed the dist file, applied UMD and used it locally, seems I'm gonna to continue using it that way until this repo has a published module with UMD support.)

Thanks anyway and sorry for not using it.
