### ISSUE TITLE
Licence Change?

### ISSUE THREAD

**Issue by kemie** [matthieua/WOW#240]
I'm pretty sure this used to be MIT-licenced. When (which version) did this change?

**Comment by vfonic** [comment]
v1.1.2
https://github.com/matthieua/WOW/tree/1.1.2

**Comment by matthieua** [comment]
Hey guys, yes that's right I added a commercial license to it and moved a GPL v3 license, I was getting too many emails about issues, questions from people using to resell themes or other commercial use cases. It's still completely free for personal use / non profits though.

**Comment by vfonic** [comment]
Version 1.1.2 is still under MIT license, since it was released under that license. That one is possible to use free of charge for any purpose, that doesn't break the MIT license.

**Comment by matthieua** [comment]
Absolutely!
