### ISSUE TITLE
element.getElementsByClassName is not a function

### ISSUE THREAD

**Issue by SimplGy** [matthieua/WOW#243]
I wish I had more detail for you here. I can't figure out what's going on, just now jumping into someone else's code base.

> Uncaught TypeError: element.getElementsByClassName is not a function
![image](https://cloud.githubusercontent.com/assets/548809/14436134/80389d4e-ffd8-11e5-96a4-46a1cd81107d.png)

![image](https://cloud.githubusercontent.com/assets/548809/14436090/490795be-ffd8-11e5-8d32-7c8f03d0342c.png)

I paused at this breakpoint. Looks like `this.element.getElementsByClassName` is a function, but `element.getElementsByClassName` is not, and the console logged value of `element` is `"0"`, a string. `this.element.parentNode` is the document, fwiw.

**Comment by SimplGy** [comment]
Looks like WOW v0.1.12

**Comment by SimplGy** [comment]
Hey sorry, that version was the giveaway. For some reason our bower file had a very old version locked in without async support. Probably the other developer had some local override so he never saw the issue.

**Comment by moroccan-webdev** [comment]
@SimplGy Hello I am having the same issue but I could not figure out what to do, I am using a template that shows up this error when I try to display a map on it. BTW I do have the same version as well as the same errors, What did you do to solve the issue?
![image](https://user-images.githubusercontent.com/23663296/85636985-dfc8d380-b679-11ea-9001-a6f2a18d5301.png)
