### ISSUE TITLE
ReactJs with WoW

### ISSUE THREAD

**Issue by QuadDepo** [matthieua/WOW#292]
Hey all,

im trying to get wowjs to work with my react app.
Anyone have an idea how?

im trying this 
`import WOW from 'wowjs';
const wow = new WOW.WOW();`

and then after my api call
`  getProjects(){
    axios.get('api')
  .then((response) => {
    console.log(response.data);
    this.setState({projects: response.data});
    wow.sync();`

i getting this error:
`typeError: Cannot read property 'nodeType' of undefined
    at WOW.exports.WOW.WOW.doSync (wow.js:285)
    at WOW.exports.WOW.WOW.sync (wow.js:276)
    at Projects.js:30
    at <anonymous>`

**Comment by QuadDepo** [comment]
WOW i finally got it working

**Comment by nunosoares27** [comment]
QuadDepo how do you solve the problem?

**Comment by QuadDepo** [comment]
I called wow.sync after i get a success on my api call
