### ISSUE TITLE
How to use wow to activate css animations on scroll?

### ISSUE THREAD

**Issue by emmadalby** [matthieua/WOW#323]
I have some percentage circles on my page and they are further down the page as a lot of content is above it - e.g; 
<div>lots of content pushing the circles down the page so that you can't see them</div>
<div>circles I'm trying to animate on scroll</div>

I would like to know how to use wow to be able to activate the circle's animation when I scroll down to them as at the moment they are activating when I cannot see them. 

My code is here:  https://codepen.io/digitalbydefault/pen/LJYPXw

Please, can anyone point me in the right direction? 

thanks

**Comment by MichaelHabib** [comment]
I assume you already fixed it ? It seems to be working as expected : animate the circle when it's in view .

**Comment by emmadalby** [comment]
Yeah, I've figured it out now. Thanks though!
