### ISSUE TITLE
Animations on Mobile

### ISSUE THREAD

**Issue by plisvb** [matthieua/WOW#34]
Great script.

Is there anyway to disable the animations on mobile devices?  I'd rather have no animations for users with a screen width of 800px or below for example.

Thanks a lot

**Comment by linkdigitaluk** [comment]
@attilaolah, thanks, it worked for me.

**Comment by cuongpx** [comment]
Its run slow in Iphone.! Hepl

**Comment by gohilinfotech** [comment]
it's not working on mobile device please help me

**Comment by Mutazalhawash** [comment]
it seems that after updating the trigger `mobile: ` false is the default value always and forever.
i am trying to activate it on mobile but it is not working

**Comment by UltraHopeful** [comment]
Try this guys It worked for me.
new WOW({mobile:false}).init();
