### ISSUE TITLE
WOW.js will only show animation one time on scrolling past it

### ISSUE THREAD

**Issue by Randall-Glass** [matthieua/WOW#46]
When you scroll past a animation and scroll back up past it, it will not do a animation again, when you scroll up past it.

I would like it so every time, you scroll past the animation, it does the animation.

**Comment by mqanneh** [comment]
+1

**Comment by ugurerkan** [comment]
Hey, have same issue then try MervelousM approach but failed because when init again wow it's reset every wow class element on my page. I need selective reset so made some changes. If you need something like that, here you are :blush:

I created a **addBox** function, it's helps push new element WOW boxes array.

```javascript
    WOW.prototype.addBox = function(element){
        this.boxes.push(element);
    };
```

Then I used jquery and [scrollspy](https://github.com/thesmart/jquery-scrollspy) plugin detect which element is out off view and then push WOW.
```javascript
    $('.wow').on('scrollSpy:exit',function(){
        var element = $(this);
        element.css({
            'visibility' : 'hidden',
            'animation-name' : 'none'
        }).removeClass('animated');
        wow.addBox(this);
    });
```

**Comment by Erick-Perea-Coronado** [comment]
Algo anda mal marca el siguiente error: ReferenceError: wow is not defined

**Comment by vivekkupadhyay** [comment]
@ugurerkan thanks a lot mate, you've saved my day.
that's really great snippet, I was really wondering what will be the best solution and you just provided already.
Thanks!

**Comment by pcortezj** [comment]
I got you fam

 function isElementInViewport(elem) {
    var $elem = $(elem);

    // Get the scroll position of the page.
    var scrollElem = ((navigator.userAgent.toLowerCase().indexOf('webkit') != -1) ? 'body' : 'html');
    var viewportTop = $(scrollElem).scrollTop();
    var viewportBottom = viewportTop + $(window).height();

    // Get the position of the element on the page.
    var elemTop = Math.round( $elem.offset().top );
    var elemBottom = elemTop + $elem.height();

    return ((elemTop < viewportBottom) && (elemBottom > viewportTop));
}

function checkAnimation() {
    var $elem = $('.wow .glyphicon-chevron-left');

    // If the animation has already been started
    if ($elem.hasClass('wow')) return;

    if (isElementInViewport($elem)) {
        // Start the animation
        new WOW().init();
    }
}

// Capture scroll events
$(window).scroll(function(){
    checkAnimation();
});

**Comment by pcortezj** [comment]
I got you fam

` function isElementInViewport(elem) {
    var $elem = $(elem);

    // Get the scroll position of the page.
    var scrollElem = ((navigator.userAgent.toLowerCase().indexOf('webkit') != -1) ? 'body' : 'html');
    var viewportTop = $(scrollElem).scrollTop();
    var viewportBottom = viewportTop + $(window).height();

    // Get the position of the element on the page.
    var elemTop = Math.round( $elem.offset().top );
    var elemBottom = elemTop + $elem.height();

    return ((elemTop < viewportBottom) && (elemBottom > viewportTop));
}

function checkAnimation() {
    var $elem = $('.wow .glyphicon-chevron-left');

    // If the animation has already been started
    if ($elem.hasClass('wow')) return;

    if (isElementInViewport($elem)) {
        // Start the animation
        new WOW().init();
    }
}

// Capture scroll events
$(window).scroll(function(){
    checkAnimation();
});
     `

**Comment by rjsnh1522** [comment]
I am getting wow is not defined .. please help me to solve this issue.

**Comment by ugurerkan** [comment]
You need to modify WOW object after wow.js loaded. @rjsnh1522 
So, please check is that javascript file or script block which is placed these modifications loaded after wow.js file.

btw, created a working example here https://jsfiddle.net/ugurerkan/53641ovn/

**Comment by rjsnh1522** [comment]
Hi,

Thanks it worked.

*Regards...*
*pawan chaurasia*
rjsh1522@gmail.com
7737295416

**Comment by Ali-Alzantot** [comment]
try to add this

window.addEventListener('scroll', function(e) {

                if( $(window).scrollTop() <= 50) {
                    $('.wow').removeClass('animated');
                    $('.wow').removeAttr('style');
                    new WOW().init();
                }
                
});

**Comment by Talha332** [comment]
it's working thanks Ali-Alzantot 💯 % working

**Comment by simsketch** [comment]
Thanks Ali-Alzantot...this is a really simple drop-in.

>     window.addEventListener('scroll', function(e) {
>             if( $(window).scrollTop() <= 50) {
>                 $('.wow').removeClass('animated');
>                 $('.wow').removeAttr('style');
>                 new WOW().init();
>             }
>     });

**Comment by kaleem7832** [comment]
i want to show animation for list and problem is all my list **contained in viewport**.
Now when i load the page, all items animate at once, but i want the items to animate one after the other.

Note: need animation of items one after the other without depending on scroll.

**Comment by djcowan** [comment]
for users of Bootstrap carousel…
`.on( 'slide.bs.carousel' , function() {
            if( $( '.my-wow-element' ).hasClass( 'wow' ) ) {
                $( this ).removeAttr( 'style' );
                new WOW().init();
            }
            // end
        } )`

**Comment by thexmanxyz** [comment]
If you want to explicitly trigger an animation for a certain element again. No need to call `init()` again and also not wanted:

```JS
var triggerAnimation = function(selector, animation) {
  var $element = $(selector);
  var element = $element[0];
  var newone = element.cloneNode(true);
  element.parentNode.replaceChild(newone, element);
	
  $element = $(selector);
  $element.addClass('wow ' + animation + ' animated');
  $element.attr('style', 'visibility: visible; animation-name: ' + animation + ';');
};

triggerAnimation('.your_selector, 'zoomIn'); // element to reanimate and animation
```

or if your use case requires to combine scroll reanimation with event animation:

```JS
var triggerAnimation = function(selector, animation) {
  var $element = $(selector);
  var applyAnimation = function(){
    $element = $(selector);
    $element.addClass('wow ' + animation + ' animated');
    $element.attr('style', 'visibility: visible; animation-name: ' + animation + ';');
  };

  // remove style and class, delay re-apply for 25ms
  if(!$element.hasClass('animated')) {
    $element.removeAttr('style');
    $element.removeClass('wow').removeClass(animation)
    setTimeout(applyAnimation, 25);
  }
};

triggerAnimation('.your_selector, 'zoomIn'); // element to reanimate and animation
```

**Comment by thexmanxyz** [comment]
> 
> 
> Hey, have same issue then try MervelousM approach but failed because when init again wow it's reset every wow class element on my page. I need selective reset, so made some changes.
> If you need something like that, here you are 😊
> 
> I created a **addBox** function, it's helps push new element WOW boxes array.
> 
> ```js
>     WOW.prototype.addBox = function(element){
>         this.boxes.push(element);
>     };
> ```
> 
> Then I used jquery and [scrollspy](https://github.com/thesmart/jquery-scrollspy) plugin detect which element is out off view and then push WOW.
> 
> ```js
>     $('.wow').on('scrollSpy:exit',function(){
>         $(this).css({
>             'visibility' : 'hidden',
>             'animation-name' : 'none'
>         }).removeClass('animated');
>         wow.addBox(this);
>     });
> ```
> 
> Here is the working example 🤗
> https://jsfiddle.net/ugurerkan/53641ovn/

If you need a solution without the necessity of the jQuery addon scrollSpy and the `scrollSpy:exit` event. Here is my solution which is quite similar but it only depends on jQuery but still needs the `addBox()` function described above.

```JS
WOW.prototype.addBox = function(element){
  this.boxes.push(element);
};
```

Additionally you have to check the viewport with the following function:

```JS
// credits @ https://stackoverflow.com/a/33979503/2379196
var isInViewport = function($container, offset) {
  var containerTop = $container.offset().top;
  var containerBottom = containerTop + $container.outerHeight();

  var viewportTop = $(window).scrollTop();
  var viewportBottom = viewportTop + $(window).height();

  return containerBottom > viewportTop && containerTop + offset < viewportBottom;
};
````
Finally find the animation which are already triggered and require a reset:

```JS
var checkWOWJsReset = function() {  
  var resetWOWJsAnimation = function() {
    var $that = $(this);
		
    // only reset animation when no long in viewport and already animated (but not running)
    if (!isInViewport($that, 0) && $that.css('animation-name') != 'none' && !$that.hasClass('animated')) {
       $that.css({'visibility': 'hidden', 'animation-name': 'none'});
       wow.addBox(this);
    }
  };
  $('.wow').each(resetWOWJsAnimation); // check if reset is necessary for any elements (you might use a different selector here)
};
$(window).on('resize scroll', checkWOWJsReset);
```
