### ISSUE TITLE
Scrolled element doesn't appear on refresh

### ISSUE THREAD

**Issue by pnpetroff** [matthieua/WOW#48]
Hi, great plugin! Using it at the moment for my project and definitely will continue using it in the future!

I stumbled on a little problem. When and element somewhere down the page is scrolled into view, it appears as it should, no problems so far, but when I refresh the page (the viewport is not reset at the top of the page), the element is in the viewport but it doesn't appear until I scroll a little.

Is there a solution to this problem?

**Comment by iamrobert** [comment]
Isotope has events - so - you can trigger onArrange when filtering.
http://isotope.metafizzy.co/events.html

```
function onArrange() {

$(".grid_item div").each(function() {
	initWowIsotope();
});

}

$grid.on( 'arrangeComplete', onArrange );

	function initWowIsotope() {
		//
		var wow = new WOW({
			boxClass: 'wow-iso',
			animateClass: 'animated',
			offset: 0, 
			mobile: true, // trigger animations on mobile devices (default is true)
			live: true, // act on asynchronously loaded content (default is true)
			callback: null,
			scrollContainer: null
		});
		void wow.offsetWidth;
		wow.init();
	}
```
.wow-iso {display: hidden;}

You can also call it something like this:
```
function onArrange() {
   $(".grid_item div").addClass("wow fade-in-up-sm");
   $(".grid_item div").attr("style","visibility: visible; animation-name: fadeInUp;");
}
```
