### ISSUE TITLE
WOW doesn't work with "One Page Scroll" plugin

### ISSUE THREAD

**Issue by sylouuu** [matthieua/WOW#61]
Hi @matthieua,

I dunno if you can make something about this.

I tested One Page Scroll: https://github.com/peachananr/onepage-scroll by @peachananr

And WOW is not triggered. Elements are not recognized in the viewport, apparently. Then, elements are always hidden.

Bests

**Comment by alvarotrigo** [comment]
It will work in [fullPage.js](https://github.com/alvarotrigo/fullPage.js) if you use it with the option `scrollBar:true` or if you use `autoScrolling:false`.

> fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by scatory** [comment]
devsite.bardstownbourbon.com causing issues on older versions of safari. Any fixes?

**Comment by anetk** [comment]
My issue is -- on my first scroll it shows but than on the second puts visibility: hidden... How to fix this?

**Comment by mahotilo** [comment]
My fix for WOW with One Page Scroll

```
wow = new WOW(
	{
		boxClass:     'wow',      // animated element css class (default is wow)
		..........
	}
)
wow.init();

$(".content").onepage_scroll({
	sectionContainer: ...
.....
	//!!!! FIX for broken WOW !!!!
	beforeMove: function(index) {
		var $section = $(".content [data-index='" + index + "']");
		$(".wow").each(function(){
			$(this).removeClass(wow.config.animateClass);
			if ( $section.has(this).length )
				wow.show(this);
               });
	},
});
```

**Comment by al404** [comment]
Any update on this?
I try code from @mahotilo but doesn't seem t work anymore
