### ISSUE TITLE
Init creates horizontal scroll

### ISSUE THREAD

**Issue by ghost** [matthieua/WOW#73]
It seems in some cases when initializing the script there is a padding being added to the right of the content, creating a horizontal scroll. Haven't been able to pinpoint what exact cases that cause this but it seems to relate to having elements positioned relative and / or fixed with a 100% width. This happens in Chrome and Safari, but in Firefox it only seems to add extra space that matches the scrollbar width (all browsers tested in OSX). Using WOW.js together with Animate.css.

**Comment by leealexey** [comment]
You can add "overflow-x: hidden;" to the "body" tag

**Comment by matias3k6** [comment]
> 
> 
> You can add "overflow-x: hidden;" to the "body" tag

That works for me
