### ISSUE TITLE
Chrome / Opera conflict issue

### ISSUE THREAD

**Issue by robbieobbie** [matthieua/WOW#76]
Hi guys,

Love the script, I use it all the time.

I am having some trouble figuring out why wow.js is disabling some background images on my site, only in Chrome and Opera. Works perfectly in Firefox and Safari. I've used this script many times before so I am assuming this is a conflict.

If this is something you can spot immediately and help with I would greatly appreciate some advice.

http://howdoyouroll.com/new/franchise/

**Comment by roryok** [comment]
I'm also having this issue

**Comment by HamiltonMilan** [comment]
I'm having the same problem, does not start the animation and the elements are left with "style = hidden". The problem is intermittent, giving refresh sometimes works sometimes not. Updated to 1.1.2 has improved but it still happens only in Chrome and Opera. IE and FF are OK

**Comment by hmahdavi921** [comment]
I use wow.js in my site It worked currently in ff but in chrome : animations run with  bounce page elements .
