### ISSUE TITLE
wow fadeInLeft do nothing

### ISSUE THREAD

**Issue by t-prod** [matthieua/WOW#97]
Hello,

Thanks for your script. I have an issue when I try an other effect fadeInLeft for instance.
No transition (fade) is done and my assets are loaded.

Is there any effects that are unavailable ?

Thanks for your help,

Regards

``` html
<div class="panel wow animated fadeInLeft">content</div>
```

**Comment by MichaelFedorchenko** [comment]
Try to remove panel class. Maybe prevent several rules.
You can see at plunker it works.
Link to Plunk: http://plnkr.co/edit/302sq0mpFE7xxO81qi8S?p=preview
